### ISSUE TITLE
The JS Logo

### ISSUE THREAD

**Issue by rohitbommisetti** [atomiks/atom-city-lights#1]
Hey I'm loving your theme! I just wanted to know what UI theme you are using with moonlight.

**Comment by atomiks** [comment]
It's the default One Dark UI + file-icons

Just to let you know, I ported this theme to VS Code and am using that now, because the new syntax highlighting grammar in Atom is too limited (tree sitter) + `language-babel` was becoming outdated + the colors became less vibrant. I am no longer updating this one 😢

**Comment by rohitbommisetti** [comment]
No problem, thanks for letting me know.
